---
- hosts: all
  become: True

  tasks:
      # DEPENDENCIES
      - name: Install dependencies
        apt:
          name: "{{ packages }}"
          update_cache: yes
        vars:
          packages:
            - build-essential
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
            - python-pip
      
      - name: Add docker key
        shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

      - name: Add docker repository
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          state: present

      - name: Install docker
        apt:
          name: "{{ packages }}"
          update_cache: yes
        vars:
          packages:
            - docker-ce
            - docker-ce-cli
            - containerd.io

      - name: Install docker module
        pip:
          name: docker

      - name: copy extra files for docker containers over
        copy:
          src: docker
          dest: /tmp

      # SETUP DOCKER CONTAINERS
      - name: Create docker network
        docker_network:
          name: csec731
          ipam_options:
            subnet: "172.1.1.0/24"
            gateway: "172.1.1.1"
            iprange: "172.1.1.0/24"
          
      - name: make webserver image
        docker_image:
          name: ubuntu-webserver
          path: /tmp/docker
          tag: latest

      - name: pull modsecurity image
        docker_image:
          name: owasp/modsecurity-crs
          tag: v3.1

      - name: copy webserver service file
        copy:
          src: docker/webserver.service
          dest: /lib/systemd/system

      - name: copy modsec service file
        copy:
          src: docker/modsec.service
          dest: /lib/systemd/system
      
      - name: enable webserver service file
        systemd:
          name: webserver
          state: started
          enabled: yes

      - name: enable modsec service file
        systemd:
          name: modsec
          state: started
          enabled: yes