---
- hosts: all
  become: True
  vars:
    ansible_ssh_private_key_file: ~/.doc/bigone.pem
    ansible_ssh_common_args: '-v -o StrictHostKeyChecking=no'


  tasks:
      # DEPENDENCIES
      - name: Install dependencies
        apt:
          name: "{{ packages }}"
          update_cache: yes
        vars:
          packages:
            - build-essential
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
            - python-pip
      
      - name: Add docker key
        shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

      - name: Add docker repository
        apt_repository:
          repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
          state: present

      - name: Install docker
        apt:
          name: "{{ packages }}"
          update_cache: yes
        vars:
          packages:
            - docker-ce
            - docker-ce-cli
            - containerd.io

      - name: Install docker module
        pip:
          name: docker

      - name: copy docker file and php script over
        copy:
          src: docker
          dest: /tmp

      # SETUP DOCKER CONTAINERS
      - name: make ubuntu container
        docker_image:
          name: webserver
          path: /tmp/docker
          tag: latest

      - name: pull modsecurity image
        docker_image:
          name: owasp/modsecurity-crs
          tag: latest
      
      - name: create ubuntu container
        docker_container:
          name: webserver-container
          image: webserver
          ports:
            - "80:8080"
            - "443:8443"
          networks:
            - name: main
              ipv4_address: "172.1.1.100"
      
      - name: create modsec container
        docker_container:
          name: modsecurity
          image: owasp/modsecurity:latest
          ports:
            - "80:80"
          networks:
            - name: main
              ipv4_address: "172.1.1.101"
          env:
            PROXY: 1
            UPSTREAM: "172.1.1.100"
